### PR TITLE
Feat: add "target: blank" option to links

### PR DESCRIPTION
**Pull request by jannescb**
This PR adds a "open link in new tab" feature as documented here https://ckeditor.com/docs/ckeditor5/latest/features/link.html#adding-target-and-rel-attributes-to-external-links
by adding manual decorators to the configs.

### CODE REVIEW

**Comment by sirtobey** [comment]
I will bump this, as we need the same feature.

**Comment by Witoso** [comment]
Thank you for the contributions, the plugin requires more updates from our side, we will try to include this one as well.

**Comment by mariansimecek** [comment]
any updates on this? Thanks

**Comment by H-Gomez** [comment]
@Witoso Any update on when this might be approved?

**Review by peturgeorgievv — APPROVED** [review]

**Comment by peturgeorgievv** [comment]
I also need this ASAP, is there something we wait to release a version with this? As I don't want to have to change to the unofficial _sh CKEditor version for strapi...

**Comment by Reinmar** [comment]
I think we should have merged this sooner, seeing the feedback. It's an opt-in feature for users, so no risk here.

**Comment by Reinmar** [comment]
Published as 0.0.13.

**Pull request merged**
